language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install click
  - pip install coveralls
  - pip install coverage

script: pytest tests.py --cov

after_success:
  - coveralls
